# Generated by Django 4.1.3 on 2024-07-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azayd', '0003_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='jobDesc',
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
