# Generated by Django 4.1.3 on 2024-07-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azayd', '0004_career_jobdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='jobImage',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
